[project]
name = "beam"
version = "0.1.0"
description = "BEAM Dependencies"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy==2.2.6",
    "pandas>=2.3.3",
    "ruff>=0.14.5",
    "scikit-learn>=1.7.2",
    "sdv>=1.29.0",
]
